name: Rails CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        TARGET_KEY: ${{ secrets.TARGET_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        TARGET_USER: ${{ secrets.TARGET_USER }}
        TARGET_HOST: ${{ secrets.TARGET_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        GEOCODING_API_KEY: ${{ secrets.GEOCODING_API_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "$PRIVATE_KEY" > bastion_key
        echo "$TARGET_KEY" > target_key
        chmod 600 bastion_key target_key
        scp -i bastion_key -o StrictHostKeyChecking=no target_key ${USER_NAME}@${HOST_NAME}:~/target_key
        ssh -i bastion_key -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} << EOF
        chmod 600 ~/target_key
        ssh -i target_key ${TARGET_USER}@${TARGET_HOST} << 'INNER'
          cd tomoni_farm
          git pull origin main
          echo "DB_USERNAME=${DB_USERNAME}" > .env.production
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.production
          echo "DB_HOST=${DB_HOST}" >> .env.production
          echo "DB_DATABASE=${DB_DATABASE}" >> .env.production
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" >> .env.production
          echo "GEOCODING_API_KEY=${GEOCODING_API_KEY}" >> .env.production
          echo "STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}" >> .env.production
          echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}" >> .env.production
          echo "STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}" >> .env.production
          echo "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}" >> .env.production
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env.production
          echo "OPENAI_API_KEY=$OPENAI_API_KEY"
          env | grep OPENAI
          export NVM_DIR="/home/${TARGET_USER}/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 16
          nvm alias default 16
          unset NODE_OPTIONS
          node -v
          yarn -v
          ~/.rbenv/shims/bundle install --path vendor/bundle --without development test
          yarn install
          source .env.production
          export $(cat .env.production | xargs)
          export NODE_ENV=production
          RAILS_ENV=production ./bin/webpack
          ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production
          ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production
          if [[ -e tmp/pids/puma.pid ]]; then
            sudo kill $(cat tmp/pids/puma.pid)
            echo "kill puma process"
          fi
          export RAILS_ENV=production
          ~/.rbenv/shims/bundle exec puma -e production -C config/puma.rb
        INNER
        EOF
        rm bastion_key target_key

        