name: Rails CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "export OPENAI_API_KEY=${OPENAI_API_KEY} && bash -s" << 'EOF'
          cd tomoni_farm
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
          git pull origin main
          export NVM_DIR="/home/ubuntu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16
          nvm alias default 16
          unset NODE_OPTIONS
          node -v
          yarn -v
          ~/.rbenv/shims/bundle install
          yarn install
          RAILS_ENV=production ./bin/webpack
          ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production
          ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production
          if [[ -e tmp/pids/puma.pid ]]; then
            sudo kill $(cat tmp/pids/puma.pid)
            echo "kill puma process"
          fi
          export RAILS_ENV=production
          ~/.rbenv/shims/bundle exec puma -C config/puma.rb
        EOF
        rm private_key
        